"""Confluence page lifecycle: create/lookup at run start, append per scenario."""
from __future__ import annotations
import json
from pathlib import Path
from ..core.event_bus import EventBus
from .claude_proc import run_claude


PROMPTS_DIR = Path(__file__).parent / "prompts"


def _substitute(template: str, vars: dict[str, str]) -> str:
    out = template
    for k, v in vars.items():
        out = out.replace("{{" + k + "}}", v)
    return out


async def run_confluence_setup(
    *, mode: str, space: str | None, page_id: str | None, run_label: str,
    codebase_path: Path, event_log: Path, bus: EventBus,
) -> int:
    """Set up the Confluence page for this run.

    mode = "create" → create a new page under `space`, write its id to the
                       event log as confluence_page_ready.
    mode = "use"    → assert the existing `page_id` is reachable, emit it as
                       confluence_page_ready.

    The subprocess writes:
      {"type": "confluence_page_ready", "data": {"page_id": "<id>", "url": "<url>"}}
    """
    if mode == "create":
        prompt = (
            "Create a new Confluence page in space "
            f"`{space}` titled "
            f"`[Explorer] {run_label}`. Use "
            "`mcp__atlassian__createConfluencePage` with contentFormat=\"markdown\" "
            "and a starter body of:\n\n"
            "```\n# Explorer run — " + run_label + "\n\n"
            "Auto-generated by the explorer. Scenarios are appended below as "
            "they complete.\n```\n\n"
            f"After creating, append ONE JSON line to the file `{event_log}` "
            "of the form:\n"
            "`{\"type\": \"confluence_page_ready\", \"data\": {\"page_id\": \"<id>\", \"url\": \"<browse url>\"}}`\n\n"
            "Do not touch the browser. Exit when done."
        )
    elif mode == "use":
        prompt = (
            f"Verify the Confluence page with id `{page_id}` exists using "
            "`mcp__atlassian__getConfluencePage`. "
            f"Then append ONE JSON line to the file `{event_log}`:\n"
            f"`{{\"type\": \"confluence_page_ready\", \"data\": {{\"page_id\": \"{page_id}\", \"url\": \"<the page browse url>\"}}}}`\n\n"
            "Do not touch the browser. Exit when done."
        )
    else:
        raise ValueError(f"unknown confluence setup mode: {mode}")

    return await run_claude(
        prompt=prompt, cwd=codebase_path,
        env_overrides={"EXPLORER_EVENT_LOG": str(event_log)},
        bus=bus, session_label="confluence-setup",
    )


async def run_confluence_writer(
    *, page_id: str, scenario_id: str, scenario_title: str, scenario_goal: str,
    scenario_status: str, bugs_filed: list[tuple[str, str]],
    screenshot_paths: list[Path], run_dir: Path, tab_url: str | None,
    codebase_path: Path, event_log: Path, bus: EventBus,
) -> int:
    """Dispatch a confluence-writer agent that appends a section for the scenario."""
    template = (PROMPTS_DIR / "system_confluence_writer.md").read_text()
    bugs_str = ", ".join(f"{k} — {t}" for k, t in bugs_filed) or "(none)"
    shots_str = "\n".join(str(p) for p in screenshot_paths) or "(none)"
    prompt = _substitute(template, {
        "CONFLUENCE_PAGE_ID": page_id,
        "SCENARIO_ID": scenario_id,
        "SCENARIO_TITLE": scenario_title,
        "SCENARIO_GOAL": scenario_goal,
        "SCENARIO_STATUS": scenario_status,
        "BUGS_FILED": bugs_str,
        "SCREENSHOT_PATHS": shots_str,
        "RUN_DIR": str(run_dir),
        "TAB_URL": tab_url or "(not configured)",
    })
    return await run_claude(
        prompt=prompt, cwd=codebase_path,
        env_overrides={"EXPLORER_EVENT_LOG": str(event_log)},
        bus=bus, session_label=f"confluence-{scenario_id}",
    )
